"""
Django settings for restorant project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ggd4rut^(58-uj&%$&#k1xnjtx7vt*^ik&)2ra)2opn0spsn_6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restorant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restorant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'myapp' / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# M-Pesa Configuration
# Get these credentials from https://developer.safaricom.co.ke/
MPESA_CONSUMER_KEY = 'YOUR_CONSUMER_KEY_HERE'
MPESA_CONSUMER_SECRET = 'YOUR_CONSUMER_SECRET_HERE'
MPESA_BUSINESS_SHORT_CODE = '174379'  # Sandbox short code
MPESA_PASSKEY = 'bfb279f9ba9b9d1380203319a73f4688'  # Sandbox passkey
MPESA_CALLBACK_URL = 'http://localhost:8000/mpesa-callback/'  # Update with your callback URL

# For production, use:
# MPESA_CONSUMER_KEY = 'YOUR_PRODUCTION_CONSUMER_KEY'
# MPESA_CONSUMER_SECRET = 'YOUR_PRODUCTION_CONSUMER_SECRET'
# MPESA_BUSINESS_SHORT_CODE = 'YOUR_PRODUCTION_SHORT_CODE'
# MPESA_PASSKEY = 'YOUR_PRODUCTION_PASSKEY'
# MPESA_CALLBACK_URL = 'https://yourdomain.com/mpesa-callback/'

# SMS Notification Configuration
# Supported SMS Providers: 'africastalking' or 'http'
SMS_PROVIDER = 'http'  # Change to 'africastalking' for Africastalking API
SMS_API_KEY = 'YOUR_SMS_API_KEY_HERE'  # Africastalking API key or HTTP gateway key
SMS_SENDER_ID = 'MAISON'  # Sender ID for SMS
SMS_ENDPOINT = ''  # HTTP endpoint for generic SMS gateway (leave empty to use console logging)

# Africastalking Configuration (if using Africastalking provider):
# 1. Sign up at https://africastalking.com/
# 2. Get API key from dashboard
# 3. Update SMS_PROVIDER = 'africastalking'
# 4. Update SMS_API_KEY with your Africastalking API key

# HTTP SMS Gateway Configuration (generic SMS provider):
# If you have an HTTP-based SMS gateway:
# SMS_ENDPOINT = 'https://your-sms-gateway.com/api/send'
# The gateway will receive: api_key, phone, message, sender_id