# Generated by Django 6.0.3 on 2026-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich'), ('salad', 'Salad'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('appetizer', 'Appetizer')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Food Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
